elasticsearch:
  image: elasticsearch:latest
  container_name: elasticsearch
  volumes:
    - ./elasticsearch:/user/share/elasticsearch/config
    - /var/log/elasticsearch:/user/share/elasticsearch/data
  ports:
    - '9200:9200'
kibana:
  container_name: kibana
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - '5601:5601'
  links:
    - elasticsearch
fluentd:
  container_name: fluentd
  build: fluentd/
  volumes:
    - /var/lib/docker/containers:/var/lib/docker/containers
  links:
    - elasticsearch
  ports:
    - '24224:24224'
